import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type Report = {
  scores: { seo: number; mobile: number; speed: number; conversion: number };
  summary: string;
  aiRecommendations?: { title: string; body: string; impact: string }[];
  keywordOpportunities?: { keyword: string; volume: number; difficulty: number }[];
  topPages?: { url: string; clicks: number; impressions: number }[];
};

export function exportReportPDF(opts: {
  siteName: string;
  websiteUrl: string;
  report: Report;
  whiteLabel?: { agencyName?: string; agencyTagline?: string };
}) {
  const { siteName, websiteUrl, report, whiteLabel } = opts;
  const doc = new jsPDF();
  const brand = whiteLabel?.agencyName || "Virtual Engine Builder";
  const tagline = whiteLabel?.agencyTagline || "AI Business Growth Infrastructure";

  doc.setFillColor(8, 13, 24);
  doc.rect(0, 0, 210, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(brand, 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(132, 204, 22);
  doc.text(tagline, 14, 24);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString(), 196, 16, { align: "right" });

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(20);
  doc.text("Website Optimization Report", 14, 50);
  doc.setFontSize(11);
  doc.setTextColor(80);
  doc.text(siteName, 14, 58);
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(websiteUrl, 14, 64);

  // Scores
  const scores = [
    ["SEO", report.scores?.seo ?? 0],
    ["Mobile", report.scores?.mobile ?? 0],
    ["Speed", report.scores?.speed ?? 0],
    ["Conversion", report.scores?.conversion ?? 0],
  ];
  let y = 76;
  doc.setFontSize(13);
  doc.setTextColor(20);
  doc.text("Scores", 14, y);
  y += 4;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Score / 100"]],
    body: scores.map(([k, v]) => [k as string, String(v)]),
    theme: "striped",
    headStyles: { fillColor: [16, 185, 129] },
  });

  // Summary
  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 30;
  y += 10;
  doc.setFontSize(13);
  doc.text("Executive summary", 14, y);
  y += 5;
  doc.setFontSize(10);
  doc.setTextColor(60);
  const lines = doc.splitTextToSize(report.summary || "—", 180);
  doc.text(lines, 14, y);
  y += lines.length * 5 + 6;

  if (report.aiRecommendations?.length) {
    doc.setFontSize(13);
    doc.setTextColor(20);
    doc.text("AI recommendations", 14, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [["Impact", "Title", "Detail"]],
      body: report.aiRecommendations.map(r => [r.impact, r.title, r.body]),
      headStyles: { fillColor: [8, 13, 24] },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 50 } },
    });
  }

  if (report.keywordOpportunities?.length) {
    autoTable(doc, {
      head: [["Keyword opportunity", "Volume", "Difficulty"]],
      body: report.keywordOpportunities.map(k => [k.keyword, String(k.volume), String(k.difficulty)]),
      headStyles: { fillColor: [16, 185, 129] },
      styles: { fontSize: 9 },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by ${brand} • Page ${i} of ${pageCount}`, 105, 290, { align: "center" });
  }

  doc.save(`${siteName.replace(/[^a-z0-9]+/gi, "-")}-optimization-report.pdf`);
}
